param(
    [Parameter(Mandatory = $true)]
    [string]$InputCsv,

    [Parameter(Mandatory = $true)]
    [string]$OutputHeader
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Convert-ToTestMethodName {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Name,

        [Parameter(Mandatory = $true)]
        [int]$Ordinal
    )

    $sanitized = [regex]::Replace($Name, "[^A-Za-z0-9_]", "_")
    if ([string]::IsNullOrWhiteSpace($sanitized)) {
        $sanitized = "Unnamed"
    }
    return "EtlCsv_{0:D3}_{1}" -f $Ordinal, $sanitized
}

function ConvertTo-Bool {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Value
    )

    $normalized = $Value.Trim().ToLowerInvariant()
    return $normalized -eq "true" -or
        $normalized -eq "1" -or
        $normalized -eq "yes" -or
        $normalized -eq "y"
}

$resolvedCsv = Resolve-Path -LiteralPath $InputCsv
$rows = @(Import-Csv -LiteralPath $resolvedCsv)

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("// Copyright (C) 2022-2023 Intel Corporation")
$lines.Add("// SPDX-License-Identifier: MIT")
$lines.Add("//")
$lines.Add("// Generated by GenerateEtlCsvTestCases.ps1 from test_cases.csv.")
$lines.Add("// Do not edit this file directly.")
$lines.Add("")

for ($i = 0; $i -lt $rows.Count; $i++) {
    $row = $rows[$i]
    if (ConvertTo-Bool -Value $row.IsExpectedFailure) {
        continue
    }

    $ordinal = $i + 1
    $methodName = Convert-ToTestMethodName -Name $row.TestName -Ordinal $ordinal

    $lines.Add("TEST_METHOD($methodName)")
    $lines.Add("{")
    $lines.Add("`tRunTestCaseFromCsvRow(testCasesCsvPath_, $i);")
    $lines.Add("}")
    $lines.Add("")
}

$content = ($lines -join "`r`n") + "`r`n"
$outputDir = Split-Path -Parent $OutputHeader
if (![string]::IsNullOrWhiteSpace($outputDir)) {
    New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
}

$encoding = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($OutputHeader, $content, $encoding)
