#pragma once
#include "../../../PresentMonAPI2/PresentMonAPI.h"

#define ALL_POINT_STATS PM_STAT_NEWEST_POINT, PM_STAT_MID_POINT

#define FULL_STATS PM_STAT_AVG, PM_STAT_PERCENTILE_99, PM_STAT_PERCENTILE_95, \
	PM_STAT_PERCENTILE_90, PM_STAT_PERCENTILE_01, PM_STAT_PERCENTILE_05, \
	PM_STAT_PERCENTILE_10, PM_STAT_MAX, PM_STAT_MIN, ALL_POINT_STATS