#pragma once
#include "../../../PresentMonAPI2/PresentMonAPI.h"

// Universal (independent) metric availability defaults for introspection.
// X_(metric_id, availability, array_size)
#define UNIVERSAL_METRIC_AVAILABILITY_LIST(X_) \
        X_(PM_METRIC_APPLICATION, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_PROCESS_ID, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_SWAP_CHAIN_ADDRESS, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_CPU_START_TIME, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_CPU_START_QPC, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_CPU_FRAME_TIME, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_CPU_BUSY, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_CPU_WAIT, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_DISPLAYED_FPS, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_APPLICATION_FPS, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_PRESENTED_FPS, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_GPU_TIME, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_GPU_BUSY, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_GPU_WAIT, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_DROPPED_FRAMES, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_DISPLAYED_TIME, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_ANIMATION_ERROR, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_ANIMATION_TIME, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_SYNC_INTERVAL, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_PRESENT_FLAGS, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_PRESENT_MODE, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_PRESENT_RUNTIME, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_ALLOWS_TEARING, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_FRAME_TYPE, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_GPU_LATENCY, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_DISPLAY_LATENCY, PM_METRIC_AVAILABILITY_AVAILABLE, 1) \
        X_(PM_METRIC_CLICK_TO_PHOTON_LATENCY, PM_METRIC_AVAILABILITY_AVAILABLE, 1)
