from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path

from pmon.common import BuildError, ensure_python_version, write_text_atomic


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate API2 ETL CSV test methods.")
    parser.add_argument("--input-csv", type=Path, required=True)
    parser.add_argument("--output-header", type=Path, required=True)
    return parser.parse_args()


def method_name(name: str, ordinal: int) -> str:
    sanitized = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not sanitized.strip():
        sanitized = "Unnamed"
    return f"EtlCsv_{ordinal:03d}_{sanitized}"


def is_true(value: str) -> bool:
    return value.strip().lower() in ("true", "1", "yes", "y")


def generate(input_csv: Path, output_header: Path) -> None:
    if not input_csv.is_file():
        raise BuildError(f"API2 test case CSV was not found: {input_csv}")
    with input_csv.open("r", encoding="utf-8-sig", newline="") as stream:
        rows = list(csv.DictReader(stream))
    lines = [
        "// Copyright (C) 2022-2023 Intel Corporation",
        "// SPDX-License-Identifier: MIT",
        "//",
        "// Generated by generate_etl_csv_tests.py from test_cases.csv.",
        "// Do not edit this file directly.",
        "",
    ]
    for row_index, row in enumerate(rows):
        if is_true(row.get("IsExpectedFailure", "")):
            continue
        name = method_name(row.get("TestName", ""), row_index + 1)
        lines.extend(
            (
                f"TEST_METHOD({name})",
                "{",
                f"\tRunTestCaseFromCsvRow(testCasesCsvPath_, {row_index});",
                "}",
                "",
            )
        )
    write_text_atomic(output_header, "\r\n".join(lines) + "\r\n")


def main() -> int:
    try:
        ensure_python_version()
        arguments = parse_arguments()
        generate(arguments.input_csv.resolve(), arguments.output_header.resolve())
        return 0
    except (BuildError, csv.Error) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
