from __future__ import annotations

import argparse
import datetime
import hashlib
import os
import subprocess
import sys
from pathlib import Path

from pmon.common import BuildError, ensure_python_version, write_text_atomic


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate the PresentMon build ID header.")
    parser.add_argument("--repo-root", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    return parser.parse_args()


def git(repo_root: Path, *arguments: str) -> str:
    command = ["git", "-C", str(repo_root), *arguments]
    try:
        result = subprocess.run(
            command,
            check=False,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    except FileNotFoundError as error:
        raise BuildError("git is required to generate the PresentMon build ID.") from error
    if result.returncode:
        raise BuildError(
            f"git command failed with exit code {result.returncode}: "
            f"{subprocess.list2cmdline(command)}\n{result.stderr}"
        )
    return result.stdout


def timestamp() -> str:
    now = datetime.datetime.now()
    return f"{now.year}.{now.month}.{now.day}.{now.hour:02d}:{now.minute:02d}:{now.second:02d}"


def build_id_content(git_hash: str, build_time: str, dirty: bool) -> str:
    git_hash = git_hash.strip() or "unknown"
    dirty_token = "true" if dirty else "false"
    lines = [
        "#pragma once",
        "// Auto-generated by versioning.py",
        "",
        f'#define PM_BID_GIT_HASH "{git_hash}"',
        f'#define PM_BID_GIT_HASH_SHORT "{git_hash[:7]}"',
        f'#define PM_BID_TIME "{build_time}"',
        f'#define PM_BID_UID "{git_hash}-{build_time}"',
        f"#define PM_BID_DIRTY {dirty_token}",
    ]
    return "\r\n".join(lines) + "\r\n"


def file_line_count(path: Path) -> int:
    with path.open("rb") as stream:
        return sum(1 for _ in stream)


def md5_hex(path: Path) -> str:
    digest = hashlib.md5()
    with path.open("rb") as stream:
        while chunk := stream.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest().upper()


def generate(repo_root: Path, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    build_id_path = output_dir / "build_id.h"
    if os.environ.get("PM_VCPKG_MODE") == "1":
        git_hash = next(
            (
                value.strip()
                for value in (
                    os.environ.get("PM_VCPKG_REF", ""),
                    os.environ.get("PM_VCPKG_SHA512", ""),
                    "BADF00D5",
                )
                if value.strip()
            ),
            "BADF00D5",
        )
        write_text_atomic(build_id_path, build_id_content(git_hash, timestamp(), False))
        print("[build_id_gen] Generated vcpkg build ID.")
        return

    git_hash = git(repo_root, "rev-parse", "HEAD").strip()
    numstat_lines = git(repo_root, "diff", "--numstat", "HEAD").splitlines()
    untracked_files = [
        value
        for value in git(repo_root, "ls-files", "--others", "--exclude-standard").splitlines()
        if value
    ]
    untracked_lines: list[str] = []
    for relative in untracked_files:
        path = repo_root / relative
        if path.is_file():
            untracked_lines.append(f"{file_line_count(path)}\t0\t{relative}")

    signature_lines = [git_hash, *numstat_lines, *untracked_lines]
    signature_a = " ".join(signature_lines)
    changed_paths: list[Path] = []
    for line in [*numstat_lines, *untracked_lines]:
        fields = line.split("\t", 2)
        if len(fields) == 3:
            relative = fields[2]
            if " => " in relative:
                relative = relative.rsplit(" => ", 1)[1].rstrip("}")
            path = repo_root / relative
            if path.is_file():
                changed_paths.append(path)
    signature_b = "".join(md5_hex(path) for path in changed_paths)

    signature_a_path = output_dir / "signature_a_prev.txt"
    signature_b_path = output_dir / "signature_b_prev.txt"
    previous_a = signature_a_path.read_text(encoding="utf-8", errors="replace") if signature_a_path.is_file() else ""
    previous_b = signature_b_path.read_text(encoding="utf-8", errors="replace") if signature_b_path.is_file() else ""
    if build_id_path.is_file() and signature_a.strip() == previous_a.strip() and signature_b.strip() == previous_b.strip():
        print("[build_id_gen] Worktree signature is unchanged; retaining build_id.h.")
        return

    write_text_atomic(signature_a_path, signature_a + "\r\n")
    write_text_atomic(signature_b_path, signature_b + "\r\n")
    dirty = bool(git(repo_root, "status", "--porcelain", "--untracked-files=normal").strip())
    write_text_atomic(build_id_path, build_id_content(git_hash, timestamp(), dirty))
    print("[build_id_gen] Generated build_id.h.")


def main() -> int:
    try:
        ensure_python_version()
        arguments = parse_arguments()
        generate(arguments.repo_root.resolve(), arguments.output_dir.resolve())
        return 0
    except (BuildError, OSError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
