include_guard(GLOBAL)

# vcpkg integration.
#
# Compiled vcpkg installations are qualified by the validated platform toolset
# family so that a v143 build and a v145 build never consume, replace, or
# reconcile away one another's packages:
#
#     build/ThirdParty/vcpkg_installed/<toolset>/<triplet>/
#
# Source downloads are toolset- and architecture-independent and stay shared at
# build/ThirdParty/vcpkg-downloads.
#
# Two selections are involved, and neither one implies the other:
#
#   1. Which vcpkg is used. The bundled fallback comes from the Visual Studio
#      instance CMake selected and published as PMON_VS_INSTANCE_ROOT; it must
#      never run its own latest-version search, because the newest installed
#      Visual Studio is not necessarily the one the generator selected.
#   2. Which toolset vcpkg compiles packages with. vcpkg runs its own
#      Visual Studio discovery and defaults VCPKG_PLATFORM_TOOLSET to the
#      newest toolset installed on the machine, so a Visual Studio 2022 build
#      would otherwise link v145 packages against the v143 STL. Generated
#      overlay triplets pin the toolset while preserving the target and host
#      triplet names.
#
# vcpkg filters its discovery by instance and by toolset separately, so the
# toolset pin alone would still allow a different installation of the same
# Visual Studio version. The instance is pinned as well, through the
# VCPKG_VISUAL_STUDIO_PATH environment variable rather than the triplet file:
# vcpkg matches it against the native installation path, and a triplet-file
# value is re-emitted unescaped into vcpkg's generated dependency-info script,
# where a native path fails to parse as CMake.

# Writes an overlay triplet that reproduces the built-in windows-static triplet
# for `architecture` and pins the validated Visual Studio platform toolset.
function(_pmon_write_vcpkg_triplet directory triplet architecture)
    file(
        WRITE "${directory}/${triplet}.cmake"
        "# Generated by PresentMonVcpkg.cmake. Do not edit.\n"
        "#\n"
        "# Reproduces the built-in ${triplet} triplet and pins the platform\n"
        "# toolset selected by the CMake generator, so that packages are\n"
        "# compiled with the same toolset that links them.\n"
        "set(VCPKG_TARGET_ARCHITECTURE ${architecture})\n"
        "set(VCPKG_CRT_LINKAGE static)\n"
        "set(VCPKG_LIBRARY_LINKAGE static)\n"
        "set(VCPKG_PLATFORM_TOOLSET ${PMON_VS_TOOLSET})\n"
    )
endfunction()

function(pmon_configure_vcpkg)
    set(
        PMON_DEPENDENCY_ROOT
        "${CMAKE_CURRENT_SOURCE_DIR}/build/ThirdParty"
        CACHE PATH
        "Shared root for restored build dependencies"
    )
    option(PMON_USE_VCPKG "Use the pinned vcpkg manifest" ON)
    option(
        PMON_AUTO_RESTORE_VCPKG
        "Allow vcpkg to restore manifest dependencies during CMake configure"
        ON
    )
    if(NOT PMON_USE_VCPKG)
        return()
    endif()

    if(NOT PMON_VS_TOOLSET OR NOT PMON_VS_INSTANCE_ROOT)
        message(
            FATAL_ERROR
            "pmon_configure_toolchain() must run before pmon_configure_vcpkg(). "
            "The validated platform toolset qualifies the vcpkg installation "
            "directory and pins the toolset vcpkg compiles packages with."
        )
    endif()

    if(NOT CMAKE_TOOLCHAIN_FILE)
        set(vcpkg_root "")
        if(DEFINED ENV{VCPKG_ROOT})
            set(vcpkg_root "$ENV{VCPKG_ROOT}")
        elseif(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake")
            set(vcpkg_root "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg")
        else()
            # The vcpkg bundled with the Visual Studio instance CMake selected.
            set(vcpkg_root "${PMON_VS_INSTANCE_ROOT}/VC/vcpkg")
        endif()

        set(vcpkg_toolchain "${vcpkg_root}/scripts/buildsystems/vcpkg.cmake")
        if(NOT EXISTS "${vcpkg_toolchain}")
            message(
                FATAL_ERROR
                "PMON_USE_VCPKG=ON, but vcpkg was not found at:\n"
                "  ${vcpkg_toolchain}\n"
                "The selected Visual Studio instance is\n"
                "  ${PMON_VS_INSTANCE_ROOT}\n"
                "Install the vcpkg component in that instance, set VCPKG_ROOT, "
                "provide a repository-local vcpkg checkout, or disable "
                "PMON_USE_VCPKG."
            )
        endif()

        set(
            CMAKE_TOOLCHAIN_FILE
            "${vcpkg_toolchain}"
            CACHE FILEPATH
            "vcpkg toolchain file"
        )
    endif()
    if(CMAKE_GENERATOR_PLATFORM STREQUAL "Win32")
        set(default_target_triplet "x86-windows-static")
    else()
        set(default_target_triplet "x64-windows-static")
    endif()
    set(VCPKG_TARGET_TRIPLET "${default_target_triplet}" CACHE STRING "vcpkg target triplet")
    set(VCPKG_HOST_TRIPLET "x64-windows-static" CACHE STRING "vcpkg host triplet")
    set(VCPKG_MANIFEST_DIR "${CMAKE_CURRENT_SOURCE_DIR}" CACHE PATH "vcpkg manifest directory")
    set(
        VCPKG_MANIFEST_INSTALL
        "${PMON_AUTO_RESTORE_VCPKG}"
        CACHE BOOL
        "Restore vcpkg manifest dependencies during configure"
    )

    # Overlay triplets keep the target and host triplet names unchanged while
    # replacing vcpkg's newest-toolset default with the validated toolset. They
    # are regenerated every configure so a Visual Studio update is picked up,
    # and they cover the host triplet as well as the target triplet.
    set(vcpkg_triplet_dir "${CMAKE_CURRENT_BINARY_DIR}/vcpkg-triplets")
    _pmon_write_vcpkg_triplet("${vcpkg_triplet_dir}" "x64-windows-static" "x64")
    _pmon_write_vcpkg_triplet("${vcpkg_triplet_dir}" "x86-windows-static" "x86")

    # PresentMon owns the overlay because these triplets pin the toolset.
    set(
        VCPKG_OVERLAY_TRIPLETS
        "${vcpkg_triplet_dir}"
        CACHE STRING
        "Overlay triplets to use for vcpkg install in manifest mode"
        FORCE
    )

    # The instance filter is a native path and is supplied per process, so it
    # never reaches the triplet file that vcpkg re-emits as CMake code.
    cmake_path(
        NATIVE_PATH PMON_VS_INSTANCE_ROOT
        NORMALIZE
        vcpkg_visual_studio_path
    )
    set(ENV{VCPKG_VISUAL_STUDIO_PATH} "${vcpkg_visual_studio_path}")

    set(
        VCPKG_INSTALLED_DIR
        "${PMON_DEPENDENCY_ROOT}/vcpkg_installed/${PMON_VS_TOOLSET}/${default_target_triplet}"
        CACHE PATH
        "Per-toolset, per-architecture vcpkg installation root"
        FORCE
    )

    # Downloaded sources are toolset- and architecture-independent.
    set(
        ENV{VCPKG_DOWNLOADS}
        "${PMON_DEPENDENCY_ROOT}/vcpkg-downloads"
    )
endfunction()
