if(NOT DEFINED PMON_ARTIFACT_MANIFEST)
    message(FATAL_ERROR "PMON_ARTIFACT_MANIFEST was not provided.")
endif()
if(NOT EXISTS "${PMON_ARTIFACT_MANIFEST}")
    message(FATAL_ERROR "Artifact manifest not found: ${PMON_ARTIFACT_MANIFEST}")
endif()

file(STRINGS "${PMON_ARTIFACT_MANIFEST}" expected_artifacts)
set(missing_artifacts "")
foreach(artifact_path IN LISTS expected_artifacts)
    if(artifact_path AND NOT EXISTS "${artifact_path}")
        list(APPEND missing_artifacts "${artifact_path}")
    endif()
endforeach()

if(missing_artifacts)
    list(JOIN missing_artifacts "\n  " missing_artifacts_text)
    message(FATAL_ERROR "Missing expected artifacts:\n  ${missing_artifacts_text}")
endif()

list(LENGTH expected_artifacts artifact_count)
message(STATUS "Verified ${artifact_count} expected PresentMon artifacts.")
